name: PR Checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: generation/go.mod
      - name: Unit Test
        run: |
          cd generation/ && go test ./...
      - name: Test Generation
        run: |
          cd generation/ && go run ./... ../raw ../gen
      - name: Build
        uses: docker/build-push-action@v7
        with:
          push: false
